server:
  port: 8081

spring:
  application:
    name: UCOCHALLENGE-SERVICE

  datasource:
    url: jdbc:postgresql://dpg-d3n8p524d50c73f4am9g-a.oregon-postgres.render.com:5432/software2terraxs?sslmode=require
    username: software2terraxs_user
    password: 8ICAjMPafawkrgj8AxFoXntuLlL0iGbF
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

services:
  parameters:
    base-url: http://localhost:8085/parameters-service/parameters/api/v1/parameters
  message:
    base-url: http://localhost:8085/message-service/messages/api/v1/messages
