server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:*"
              - "http://127.0.0.1:*"
              - "http://192.168.*.*:*"
              - "http://10.*.*.*:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
<<<<<<< HEAD
        - id: auth-service
          uri: lb://CLIENT-APP
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
=======
        - id: parameters-microservice
          uri: lb://PARAMETERS-SERVICE
          predicates:
            - Path=/parameters/api/v1/parameters/**
        - id: uco-challenge
          uri: lb://UCOCHALLENGE
          predicates:
            - Path=/uco-challenge/api/v1/users/**
        - id: message-service
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/messages/api/v1/messages/**
>>>>>>> 9a3cea5567b6387ddb4cb794f64168d34849003f

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: read-only
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
